trigger:
 tags:
    include:
    - release*

pool:
  vmImage: ubuntu-22.04
  
variables:
- group: pipeline

steps:

 - checkout: self
   persistCredentials: true
  
 - script: dotnet build --configuration release
   displayName: 'Build All Projects'

 - script: dotnet pack UnifiedAttestation/UnifiedAttestation.csproj --configuration Release --output $(Build.ArtifactStagingDirectory)/release
   displayName: 'pack UnifiedAttestation'

 - script: dotnet pack UnifiedAttestation.Functions/UnifiedAttestation.Functions.csproj --configuration Release --output $(Build.ArtifactStagingDirectory)/release
   displayName: 'pack UnifiedAttestation.Functions'

 - task: NuGetToolInstaller@1
   inputs:
    versionSpec: '6.9.1'

 - task: NuGetCommand@2
   displayName: 'Push Packages' 
   inputs:
    command: 'custom'
    arguments: 'push "$(Build.ArtifactStagingDirectory)/release/**/*.nupkg" -Source https://api.nuget.org/v3/index.json -ApiKey $(ShiftSoftwareNugetApiKey)'
