using System;

namespace ShiftSoftware.UnifiedAttestation.Utilities
{
    /// <summary>
    /// Base64 helpers shared by the HMS SysIntegrity verification path.
    /// </summary>
    internal static class Base64Utility
    {
        /// <summary>
        /// Decodes a Base64 string that may be encoded with either the standard or the URL safe alphabet, with or
        /// without padding.
        /// </summary>
        /// <remarks>
        /// HMS mixes both: the JWS segments are Base64Url, while the <c>x5c</c> certificates use standard Base64. The
        /// nonce is generated by the client, so its alphabet depends on how the client encoded it before sending it in
        /// the header.
        /// </remarks>
        /// <returns>True when the value could be decoded; otherwise, false.</returns>
        public static bool TryDecodeRelaxed(string? value, out byte[] bytes)
        {
            bytes = Array.Empty<byte>();

            if (string.IsNullOrWhiteSpace(value))
                return false;

            var normalized = value.Trim().Replace('-', '+').Replace('_', '/');

            switch (normalized.Length % 4)
            {
                case 2: normalized += "=="; break;
                case 3: normalized += "="; break;
                case 1: return false;
            }

            try
            {
                bytes = Convert.FromBase64String(normalized);
                return true;
            }
            catch (FormatException)
            {
                return false;
            }
        }
    }
}
