using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using ShiftSoftware.UnifiedAttestation.Models.HMS;
using ShiftSoftware.UnifiedAttestation.Services.Interfaces;
using ShiftSoftware.UnifiedAttestation.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;

namespace ShiftSoftware.UnifiedAttestation.Services
{
    /// <summary>
    /// Verifies Huawei Mobile Services (HMS) SafetyDetect SysIntegrity results.
    /// </summary>
    /// <remarks>
    /// Unlike <see cref="HMSUserDetectService"/>, verification is performed entirely on this server with no call to
    /// Huawei and no OAuth credentials. The device returns a JWS which is validated by checking its certificate chain
    /// against the HUAWEI CBG Root CA, confirming the leaf certificate was issued for
    /// <c>sysintegrity.platform.hicloud.com</c>, verifying the signature, and finally applying the payload policy
    /// configured in <see cref="HMSSysIntegrityOptions"/>. The root CA is supplied directly through
    /// <see cref="HMSSysIntegrityOptions.RootCertificatePem"/>.
    /// </remarks>
    public class HMSSysIntegrityService
    {
        /// <summary>
        /// The host name the leaf certificate of a genuine SysIntegrity result is issued for.
        /// </summary>
        private const string SysIntegrityHostName = "sysintegrity.platform.hicloud.com";

        private const string SubjectAlternativeNameOid = "2.5.29.17";

        private readonly ILogger<HMSSysIntegrityService> logger;
        private readonly HMSSysIntegrityOptions options;
        private readonly INonceValidator nonceValidator;

        public HMSSysIntegrityService(ILogger<HMSSysIntegrityService> logger,
            IOptions<HMSSysIntegrityOptions> options,
            INonceValidator nonceValidator)
        {
            this.logger = logger;
            this.options = options.Value;
            this.nonceValidator = nonceValidator;
        }

        /// <summary>
        /// Verifies an HMS SafetyDetect SysIntegrity JWS produced by the HMS Core SDK on the device.
        /// </summary>
        /// <remarks>
        /// This method performs the following steps:
        /// <list type="bullet">
        /// <item>Splits the JWS and reads the certificate chain from its <c>x5c</c> header.</item>
        /// <item>Validates that chain against the configured HUAWEI CBG Root CA.</item>
        /// <item>Confirms the leaf certificate was issued for <c>sysintegrity.platform.hicloud.com</c>.</item>
        /// <item>Verifies the signature over the JWS header and payload using the leaf certificate's public key.</item>
        /// <item>Applies the configured payload policy: basic integrity, package name, signing certificate digest, age and nonce.</item>
        /// </list>
        /// </remarks>
        /// <param name="jws">The SysIntegrity result string generated by the HMS Core SDK on the mobile device.</param>
        /// <param name="nonce">The nonce the client passed to the SysIntegrity API, echoed back through the nonce header.</param>
        /// <returns>
        /// <see langword="true"/> if the JWS is authentic and the payload satisfies the configured policy; otherwise, <see langword="false"/>.
        /// </returns>
        public async ValueTask<bool> VerifyTokenAsync(string jws, string? nonce)
        {
            if (string.IsNullOrWhiteSpace(jws))
            {
                logger.LogError("HMS SysIntegrity verification failed: the token is empty.");
                return false;
            }

            var segments = jws.Split('.');

            if (segments.Length != 3)
            {
                logger.LogError("HMS SysIntegrity verification failed: expected 3 JWS segments but found {SegmentCount}.", segments.Length);
                return false;
            }

            try
            {
                using var rootCertificate = ReadRootCertificate();

                if (rootCertificate is null)
                    return false;

                if (!Base64Utility.TryDecodeRelaxed(segments[0], out var headerBytes)
                    || !Base64Utility.TryDecodeRelaxed(segments[1], out var payloadBytes)
                    || !Base64Utility.TryDecodeRelaxed(segments[2], out var signature))
                {
                    logger.LogError("HMS SysIntegrity verification failed: the JWS is not valid Base64Url.");
                    return false;
                }

                var header = JsonSerializer.Deserialize<HMSSysIntegrityJwsHeader>(headerBytes);

                if (header is null || header.X5C is null || header.X5C.Count == 0)
                {
                    logger.LogError("HMS SysIntegrity verification failed: the JWS header carries no certificate chain.");
                    return false;
                }

                // Only these two are produced by SafetyDetect. Anything else (including "none") is rejected outright so
                // the algorithm named in the untrusted header can never weaken verification.
                RSASignaturePadding padding;
                switch (header.Algorithm)
                {
                    case "RS256":
                        padding = RSASignaturePadding.Pkcs1;
                        break;
                    case "PS256":
                        padding = RSASignaturePadding.Pss;
                        break;
                    default:
                        logger.LogError("HMS SysIntegrity verification failed: unsupported signing algorithm '{Algorithm}'.", header.Algorithm);
                        return false;
                }

                var chain = new List<X509Certificate2>();

                try
                {
                    foreach (var encodedCertificate in header.X5C)
                    {
                        // The x5c entries use the standard Base64 alphabet, unlike the JWS segments themselves.
                        if (!Base64Utility.TryDecodeRelaxed(encodedCertificate, out var certificateBytes))
                        {
                            logger.LogError("HMS SysIntegrity verification failed: a certificate in the chain is not valid Base64.");
                            return false;
                        }

                        chain.Add(new X509Certificate2(certificateBytes));
                    }

                    var leaf = chain[0];

                    if (!VerifyCertificateChain(chain, rootCertificate))
                        return false;

                    if (!VerifyHostName(leaf))
                        return false;

                    var signContent = Encoding.ASCII.GetBytes($"{segments[0]}.{segments[1]}");

                    using var publicKey = leaf.GetRSAPublicKey();

                    if (publicKey is null)
                    {
                        logger.LogError("HMS SysIntegrity verification failed: the leaf certificate carries no RSA public key.");
                        return false;
                    }

                    if (!publicKey.VerifyData(signContent, signature, HashAlgorithmName.SHA256, padding))
                    {
                        logger.LogError("HMS SysIntegrity verification failed: the signature does not match.");
                        return false;
                    }
                }
                finally
                {
                    foreach (var certificate in chain)
                        certificate.Dispose();
                }

                var payload = JsonSerializer.Deserialize<HMSSysIntegrityPayload>(payloadBytes);

                if (payload is null)
                {
                    logger.LogError("HMS SysIntegrity verification failed: the payload could not be read.");
                    return false;
                }

                logger.LogInformation("HMS SysIntegrity Result:\n{@Result}", Encoding.UTF8.GetString(payloadBytes));

                return await VerifyPayloadAsync(payload, nonce);
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "HMS SysIntegrity verification failed");
                return false;
            }
        }

        /// <summary>
        /// Applies the configured policy to an already authenticated payload.
        /// </summary>
        private async ValueTask<bool> VerifyPayloadAsync(HMSSysIntegrityPayload payload, string? nonce)
        {
            if (!payload.BasicIntegrity)
            {
                logger.LogWarning("HMS SysIntegrity rejected: basicIntegrity is false. Advice: {Advice}", payload.Advice);
                return false;
            }

            if (!options.AllowedPackageNames.Contains(payload.APKPackageName ?? string.Empty, StringComparer.Ordinal))
            {
                logger.LogWarning("HMS SysIntegrity rejected: package name '{PackageName}' is not allowed.", payload.APKPackageName);
                return false;
            }

            if (payload.APKCertificateDigestSha256 is null
                || !payload.APKCertificateDigestSha256.Any(x => options.AllowedApkCertificateDigests.Contains(x, StringComparer.Ordinal)))
            {
                logger.LogWarning("HMS SysIntegrity rejected: no app signing certificate digest matched the allow list.");
                return false;
            }

            var issuedAt = DateTimeOffset.FromUnixTimeMilliseconds(payload.TimestampMs);
            var age = DateTimeOffset.UtcNow - issuedAt;

            if (age > options.MaxTokenAge)
            {
                logger.LogWarning("HMS SysIntegrity rejected: the result is {Age} old, which exceeds the maximum of {MaxTokenAge}.", age, options.MaxTokenAge);
                return false;
            }

            if (age < -options.ClockSkew)
            {
                logger.LogWarning("HMS SysIntegrity rejected: the result is dated {IssuedAt}, which is too far in the future.", issuedAt);
                return false;
            }

            if (options.RequireNonce && !await nonceValidator.ValidateAsync(nonce, payload.Nonce))
            {
                logger.LogWarning("HMS SysIntegrity rejected: the nonce did not validate.");
                return false;
            }

            return true;
        }

        /// <summary>
        /// Validates the JWS certificate chain against the HUAWEI CBG Root CA, which is the only trusted root for this check.
        /// </summary>
        private bool VerifyCertificateChain(List<X509Certificate2> certificates, X509Certificate2 rootCertificate)
        {
            using var chain = new X509Chain();

            chain.ChainPolicy.TrustMode = X509ChainTrustMode.CustomRootTrust;
            chain.ChainPolicy.CustomTrustStore.Add(rootCertificate);

            // Everything above the leaf is supplied by the token itself, so it goes into the extra store rather than
            // being resolved from the machine's certificate stores.
            for (var i = 1; i < certificates.Count; i++)
                chain.ChainPolicy.ExtraStore.Add(certificates[i]);

            // The chain is delivered inside the token and validated against a pinned root, so there is no revocation
            // endpoint to consult. This matches Huawei's own server sample.
            chain.ChainPolicy.RevocationMode = X509RevocationMode.NoCheck;

            if (chain.Build(certificates[0]))
                return true;

            logger.LogError("HMS SysIntegrity verification failed: certificate chain validation failed. Status: {ChainStatus}",
                string.Join("; ", chain.ChainStatus.Select(x => $"{x.Status}: {x.StatusInformation?.Trim()}")));

            return false;
        }

        /// <summary>
        /// Confirms the leaf certificate was issued for <see cref="SysIntegrityHostName"/>.
        /// </summary>
        private bool VerifyHostName(X509Certificate2 leaf)
        {
            var names = new List<string>();

            var subjectAlternativeName = leaf.Extensions
                .FirstOrDefault(x => string.Equals(x.Oid?.Value, SubjectAlternativeNameOid, StringComparison.Ordinal));

            if (subjectAlternativeName is not null)
            {
                var typed = new X509SubjectAlternativeNameExtension(subjectAlternativeName.RawData, subjectAlternativeName.Critical);
                names.AddRange(typed.EnumerateDnsNames());
            }

            // Fall back to the common name for certificates that predate the SAN requirement.
            if (names.Count == 0)
            {
                var commonName = leaf.GetNameInfo(X509NameType.DnsName, forIssuer: false);

                if (!string.IsNullOrWhiteSpace(commonName))
                    names.Add(commonName);
            }

            if (names.Any(MatchesSysIntegrityHost))
                return true;

            logger.LogError("HMS SysIntegrity verification failed: the leaf certificate is issued for [{Names}] and not for {ExpectedHost}.",
                string.Join(", ", names), SysIntegrityHostName);

            return false;
        }

        /// <summary>
        /// Matches a certificate DNS name against <see cref="SysIntegrityHostName"/>, allowing a single leading wildcard
        /// label the same way a standard TLS host name verifier does.
        /// </summary>
        private static bool MatchesSysIntegrityHost(string name)
        {
            if (string.Equals(name, SysIntegrityHostName, StringComparison.OrdinalIgnoreCase))
                return true;

            if (!name.StartsWith("*.", StringComparison.Ordinal))
                return false;

            // A wildcard covers exactly one label, so the remainder must match and must not itself contain a dot.
            var suffix = name.Substring(1);
            var firstDot = SysIntegrityHostName.IndexOf('.');

            return firstDot > 0
                && string.Equals(SysIntegrityHostName.Substring(firstDot), suffix, StringComparison.OrdinalIgnoreCase);
        }

        /// <summary>
        /// Reads the configured HUAWEI CBG Root CA. Parsing is cheap and the value is fixed for the process, so it is read
        /// per request rather than cached, and the caller disposes it.
        /// </summary>
        /// <remarks>
        /// The value comes from <see cref="HMSSysIntegrityOptions.RootCertificatePem"/> and may be PEM text or Base64
        /// encoded DER.
        /// </remarks>
        private X509Certificate2? ReadRootCertificate()
        {
            try
            {
                return ReadCertificate(options.RootCertificatePem!);
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Failed to read the HMS SysIntegrity root certificate from RootCertificatePem.");

                return null;
            }
        }

        /// <summary>
        /// Reads a certificate from either PEM text or Base64 encoded DER, so the value can be supplied in whichever
        /// form the downloaded root CA happens to be in.
        /// </summary>
        private static X509Certificate2 ReadCertificate(string value)
        {
            if (value.Contains("-----BEGIN CERTIFICATE-----", StringComparison.Ordinal))
                return X509Certificate2.CreateFromPem(value);

            if (Base64Utility.TryDecodeRelaxed(RemoveWhiteSpace(value), out var der))
                return new X509Certificate2(der);

            throw new FormatException("The root certificate secret is neither PEM text nor Base64 encoded DER.");
        }

        /// <summary>
        /// Strips the line breaks a Base64 encoded certificate is usually wrapped at.
        /// </summary>
        private static string RemoveWhiteSpace(string value)
        {
            var builder = new StringBuilder(value.Length);

            foreach (var character in value)
            {
                if (!char.IsWhiteSpace(character))
                    builder.Append(character);
            }

            return builder.ToString();
        }
    }
}
